# Generated by Django 2.2.5 on 2019-09-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='stores',
            field=models.ManyToManyField(to='menuserver.Stores'),
        ),
        migrations.DeleteModel(
            name='storeManager',
        ),
    ]
