# Generated by Django 2.2.5 on 2019-09-20 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categary', models.CharField(max_length=50)),
                ('photo_url', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'dish',
                'verbose_name_plural': 'dishes',
            },
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manager_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'manager',
                'verbose_name_plural': 'managers',
                'db_table': 'Manager',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('order_id', models.CharField(max_length=100)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuserver.Dishes')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
            },
        ),
        migrations.CreateModel(
            name='SubmittedOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('username', models.CharField(default='Null', max_length=100)),
                ('is_fulfill', models.BooleanField(default=False)),
                ('order', models.ManyToManyField(to='menuserver.Orders')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuserver.Stores')),
            ],
            options={
                'verbose_name': 'submittedorder',
                'verbose_name_plural': 'submittedorders',
            },
        ),
        migrations.CreateModel(
            name='storeManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuserver.Managers')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuserver.Stores')),
            ],
        ),
        migrations.AddField(
            model_name='managers',
            name='stores',
            field=models.ManyToManyField(related_name='managers', to='menuserver.Stores'),
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('stores', models.ManyToManyField(to='menuserver.Stores')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
    ]
